export const RESOURCES = {
  PLACEHOLDERS: {
    EMAIL: "johndoe@company.com",
    IDENTITY: "john.doe",
    PASSWORD_LOGIN: "••••••••••••",
    PASSWORD_REGISTER: "••••••••",
    FULLNAME: "John Doe",
    USERNAME: "johndoe",
    TODO_TASK: "What needs to be done?",
    SQL_QUERY: "select * from todo;"
  },
  COMMON: {
    BACK: "Back",
    SUBMIT: "Submit",
    SIGN_IN: "Sign In",
    SIGN_OUT: "Sign Out",
    REGISTER: "Register",
    LOGO_BRAND: "Todo Vibe",
    REQUIRED: "Required",
    INVALID_FORMAT: "Invalid format",
    LOADING: "Loading",
    PREPARING: "Optimizing Neural Pathways...",
    ERROR: "Error",
    SUCCESS: "Success",
    RETURN_TO_LOGIN: "Return to Login",
    SCROLL_TO_TOP: "Scroll to top",
  },
  AUTH: {
    PLEASE_SIGN_IN: "Please sign in with your preferred option",
    ENTERPRISE_SSO: "Enterprise SSO",
    ACTIVE_DIRECTORY: "Active Directory",
    USERNAME_OR_EMAIL: "Username or Email",
    PASSWORD: "Password",
    FORGOT_PASSWORD: "Forgot Password",
    FORGOT_LINK: "Forgot?",
    REMEMBER_ME: "Remember me",
    REGISTER_LINK: "REGISTER",
    SIGNING_IN: "Signing in...",
    LOGIN_FAILED: "Login failed",
    CREATING_ACCOUNT: "Creating account...",
    REGISTRATION_FAILED: "Registration failed",
    SENDING_RESET_LINK: "Sending reset link...",
    RESET_LINK_SENT: "If an account exists with this email, you will receive a password reset link.",
    NEW_USER: "New User",
    FULL_NAME: "Full Name",
    USERNAME: "Username",
    EMAIL: "Email",
    FORGOT_PASSWORD_TITLE: "Forgot Password",
    FORGOT_PASSWORD_DESC: "Enter your registered email to proceed with account recovery process",
    RELAY_SUCCESS: "Relay Success",
    PASSWORD_COMPLEXITY: "Min 8 characters\n1 uppercase\n1 lowercase\n1 number\n1 special Symbol",
    EMAIL_HINT: "Please enter a valid email address",
  },
  TODO: {
    TITLE: "My Tasks",
    SUBTITLE: "Stay organized and productive.",
    ADD_TASK: "Add",
    LOADING_TASKS: "Loading tasks...",
    ADDING: "Adding...",
    REOPENING: "Reopening...",
    COMPLETING: "Completing...",
    DELETING: "Deleting...",
    NO_TASKS: "No tasks yet. Enjoy your day!",
    DELETE_ARIA: "Delete todo",
    TASK_DETAILS: "Task Details",
    LOADING_TASK_MESSAGE: "Loading your tasks...",
  },
  NAV: {
    HOME: "Home",
    TASKS: "Tasks",
    SQL: "SQL",
    ERROR: "Error",
  },
  THEME: {
    SWITCH_TO_LIGHT: "Switch to light mode",
    SWITCH_TO_DARK: "Switch to dark mode",
    CENTERED_VIEW: "Centered View",
    WIDE_VIEW: "Wide View",
    BG_PATTERN: "Background Pattern",
    COLOR_THEME: "Color Theme",
  },
  SQL: {
    TITLE: "SQL Explorer",
    SUBTITLE: "Query your data directly.",
    QUERY_LABEL: "SQL Query",
    SHORTCUT_HINT: "Ctrl + Enter to execute",
    EXECUTING_QUERY: "Executing Query...",
    FAILED_TO_EXECUTE: "Failed to execute query",
    EXECUTING: "Executing...",
    EXECUTE: "Execute",
    CLEAR: "Clear",
    MORE_INFO: "More Info",
    NO_RESULTS: "Query executed successfully with no results.",
    ERROR_DETAILS_TITLE: "SQL Execution Error Details",
    NULL_VALUE: "null",
  },
  ERROR_PAGE: {
    TITLE: "Error",
    SUBTITLE: "Showcase",
    DESCRIPTION: "Select a system failure signature to simulate global modal feedback.",
    BACKEND_API: "Backend API:",
    ONLINE: "Online",
    OFFLINE: "Offline Mode",
    SYNCING: "Synchronizing failure signature...",
    SELECT_PREVIEW: "Select an error code to preview",
    METADATA_UNAVAILABLE: "Detailed metadata synchronization unavailable.",
    APP_ERROR_DETAILS: "Application Error Details",
    NOT_FOUND: "The page you're looking for doesn't exist.",
  },
  HOME: {
    HERO_TITLE: "Organize your life with",
    HERO_SUBTITLE: "A premium task management experience built with Micronaut, DuckDB, and SolidJS. Track your goals, explore your data, and stay in the flow.",
    GET_STARTED: "Get Started",
    FEAT_TASK_TITLE: "Task Management",
    FEAT_TASK_DESC: "Streamlined interface for creating and managing your daily tasks with ease.",
    FEAT_THEME_TITLE: "Adaptive Theme",
    FEAT_THEME_DESC: "Seamlessly switch between Light and Dark modes to suit your work environment.",
    FEAT_SQL_TITLE: "SQL Power",
    FEAT_SQL_DESC: "Advanced users can query the underlying DuckDB database directly using raw SQL.",
  },
  PRIORITY: {
    P1: "Priority 1",
    P2: "Priority 2",
    P3: "Priority 3",
    P4: "Priority 4",
    P5: "Priority 5",
    P1_SHORT: "P1",
    P2_SHORT: "P2",
    P3_SHORT: "P3",
    P4_SHORT: "P4",
    P5_SHORT: "P5",
  },
  ERROR_CATALOG: {
    E400: { NAME: "Bad Request", DESCRIPTION: "The message was garbled by space debris. Our computers can't make sense of your request." },
    E401: { NAME: "Unauthorized", DESCRIPTION: "Halt! You haven't scanned your DNA at the security terminal yet. Show us your credentials." },
    E402: { NAME: "Payment Required", DESCRIPTION: "Your galactic credit balance is zero. Please deposit some tokens to proceed through the toll gate." },
    E403: { NAME: "Forbidden", DESCRIPTION: "Our security bots have flagged your entry. You don't have the clearance for this quadrant." },
    E404: { NAME: "Not Found", DESCRIPTION: "We've scanned the entire sector, but this page seems to have disappeared into a black hole." },
    E405: { NAME: "Method Not Allowed", DESCRIPTION: "You're trying to perform a maneuver that's prohibited in this gravity well." },
    E406: { NAME: "Not Acceptable", DESCRIPTION: "Our sensors can't process the data format you're sending. It's like talking to an alien." },
    E407: { NAME: "Proxy Authentication Required", DESCRIPTION: "The gateway requires DNA verification from a recognized proxy server before letting you pass." },
    E408: { NAME: "Request Timeout", DESCRIPTION: "Our signals got lost in deep space. The connection dissipated before we could finish." },
    E409: { NAME: "Conflict", DESCRIPTION: "Two versions of the same reality are trying to exist at once. Please resolve the paradox." },
    E410: { NAME: "Gone", DESCRIPTION: "This resource used to exist, but it's been vaporized. It's gone forever from the starmaps." },
    E411: { NAME: "Length Required", DESCRIPTION: "The message is missing its size metadata. We need to know how big the shipment is." },
    E412: { NAME: "Precondition Failed", DESCRIPTION: "The atmospheric conditions aren't right. Your preconditions for this request weren't met." },
    E413: { NAME: "Payload Too Large", DESCRIPTION: "The payload is too heavy for our tractor beams to lift. Try sending a smaller batch." },
    E414: { NAME: "URI Too Long", DESCRIPTION: "The flight path you specified is too complex for our navigation computers to plot." },
    E415: { NAME: "Unsupported Media Type", DESCRIPTION: "The media type you sent is built with unknown technology. We can't interface with it." },
    E416: { NAME: "Range Not Satisfiable", DESCRIPTION: "You're asking for a data range that's outside the known boundaries of this archive." },
    E417: { NAME: "Expectation Failed", DESCRIPTION: "Our station couldn't meet the high expectations set in your transmission headers." },
    E418: { NAME: "I'm a teapot", DESCRIPTION: "I'm a short and stout teapot. I refuse to brew coffee in this high-tech space lab." },
    E421: { NAME: "Misdirected Request", DESCRIPTION: "Your ship arrived at the wrong docking bay. This server isn't configured for this request." },
    E422: { NAME: "Unprocessable Entity", DESCRIPTION: "The instructions are syntactically correct but logically impossible in this reality." },
    E423: { NAME: "Locked", DESCRIPTION: "The resource is currently locked in a stasis field. Try again once it's released." },
    E424: { NAME: "Failed Dependency", DESCRIPTION: "The request failed because its dependent mission was aborted or failed." },
    E425: { NAME: "Too Early", DESCRIPTION: "You're trying to jump to warp before the engines have even started spinning up." },
    E426: { NAME: "Upgrade Required", DESCRIPTION: "Your ship's firmware is too old. You need to upgrade your protocol to proceed." },
    E428: { NAME: "Precondition Required", DESCRIPTION: "The server requires a complete pre-flight checklist before it can process this." },
    E429: { NAME: "Too Many Requests", DESCRIPTION: "Too many ships are trying to pass through the warp gate at once. Please wait your turn." },
    E431: { NAME: "Request Header Fields Too Large", DESCRIPTION: "The metadata you sent is so heavy it's causing local gravitational distortions." },
    E451: { NAME: "Unavailable For Legal Reasons", DESCRIPTION: "By order of the Galactic Council, access to this resource has been legally restricted." },
    E500: { NAME: "Internal Server Error", DESCRIPTION: "The engines are overheating! Something went wrong on the server, and our engineers have been alerted." },
    E501: { NAME: "Not Implemented", DESCRIPTION: "We haven't finished building this part of the ship yet. Try again in a future update." },
    E502: { NAME: "Bad Gateway", DESCRIPTION: "The jump gate is flickering. The relay station isn't responding correctly." },
    E503: { NAME: "Service Unavailable", DESCRIPTION: "The station is undergoing maintenance. We'll be back online once the fusion reactor restarts." },
    E504: { NAME: "Gateway Timeout", DESCRIPTION: "The long-range communications array is lagging. The server response took too long to arrive." },
    E505: { NAME: "HTTP Version Not Supported", DESCRIPTION: "We're using different versions of the communication protocol. We can't shake hands." },
    E506: { NAME: "Variant Also Negotiates", DESCRIPTION: "The server is caught in an infinite negotiation loop. We're going in circles!" },
    E507: { NAME: "Insufficient Storage", DESCRIPTION: "We don't have enough storage space left on the station to hold your data." },
    E508: { NAME: "Loop Detected", DESCRIPTION: "Your request keeps coming back to us in a loop. We've hit a temporal anomaly." },
    E510: { NAME: "Not Extended", DESCRIPTION: "The server needs further extensions to fulfill this request. We're missing some modules." },
    E511: { NAME: "Network Authentication Required", DESCRIPTION: "You need to authenticate with the relay network before we can forward your signal." },
    UNKNOWN: { NAME: "Unexpected Anomaly", DESCRIPTION: "A glitch in the matrix occurred. We're not sure what it is, but it's definitely not supposed to be here." }
  },
  COMPONENTS: {
    DATA_MODAL: {
      ENTRY_DETAILS: "Entry Details",
      RECORD_IDENTIFIER: "Record Identifier",
      NOT_SPECIFIED: "Not specified (NULL)",
      CLOSE_VIEW: "Close View",
      DAY: "Day",
      DATE: "Date",
      TIME: "Time",
      TIMEZONE: "Timezone",
    },
    DATA_TABLE: {
      NULL_VALUE: "null",
    },
    PAGINATION: {
      TOTAL_RECORDS: "Total records",
      FIRST_PAGE: "First page",
      PREVIOUS_PAGE: "Previous page",
      NEXT_PAGE: "Next page",
      LAST_PAGE: "Last page",
      ROW_PER_PAGE: "Row per page",
      DOWNLOAD_RESULTS: "Download results",
    }
  }
} as const;
